# Generated by Django 2.1.3 on 2018-11-09 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('name', models.CharField(max_length=2048, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('word', models.CharField(max_length=64, verbose_name='Ключевое слово')),
                ('weight', models.FloatField(null=True, verbose_name='Вес')),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='memes.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('image_url', models.CharField(max_length=2048, verbose_name='Путь к изображению')),
                ('raw_text', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Текст')),
                ('ru_text', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Русский текст')),
                ('en_text', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Английский текст')),
                ('lem_text', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Лемматизированный текст')),
                ('labels', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Сущности на фото')),
                ('cluster_label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cluster_label', to='memes.Cluster')),
                ('cluster_text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cluster_text', to='memes.Cluster')),
            ],
        ),
    ]
