# Generated by Django 2.1.3 on 2018-11-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='requests',
            field=models.IntegerField(default=0, verbose_name='Количество запросов за последние 24 часа'),
        ),
    ]
