# Generated by Django 2.0.2 on 2018-11-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_cluster_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='requests',
            field=models.IntegerField(verbose_name='Количество запросов за последние 24 часа'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='cluster_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cluster_label', to='memes.Cluster'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='cluster_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cluster_text', to='memes.Cluster'),
        ),
    ]
