# Generated by Django 2.0.2 on 2018-11-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20181110_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='en_text',
            field=models.CharField(blank=True, max_length=16348, null=True, verbose_name='Английский текст'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='labels',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Сущности на фото'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='lem_text',
            field=models.CharField(blank=True, max_length=16348, null=True, verbose_name='Лемматизированный текст'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='raw_text',
            field=models.CharField(blank=True, max_length=16348, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='ru_text',
            field=models.CharField(blank=True, max_length=16438, null=True, verbose_name='Русский текст'),
        ),
    ]
